---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)-20s%(levelname)-8s%(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
    test:
        class: test.MultiProcessingLog
        level: DEBUG
        formatter: simple
        name: test.log
        mode: a
        maxsize: 1024
        rotate: 0
root:
    level: DEBUG
    handlers: [console, test]